#! /bin/sh

# Vars
padding=0

# Autostart
#fixwifi $ 				    # Crashes
sxhkd & 
picom & 
dunst &
redshift -l 52.007229:5.556170 &
nitrogen --restore & 
polybar mainbar-bspwm & 
polybar bspwm_two & 

# Misc Settings
xsetroot -cursor_name left_ptr &    # Make sure to keep the cursor a pointer when not on window
xinput set-prop 'ELAN1300:00 04F3:3057 Touchpad' 304 1 # Set mousepad
xinput set-prop 'ELAN1300:00 04F3:3057 Touchpad' 322 1 # Enable tapping


# Monitors
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 
bspc monitor HDMI-2 -d 1 2 3 4 5 6 7 8 9


# Config
bspc config border_width         2	    # Width of window border
bspc config window_gap		 10	    # Gap between windows
bspc config split_ratio          0.50	    # 
bspc config borderless_monocle   true	    #
bspc config gapless_monocle      true	    #
bspc config focus_follows_pointer false 
bspc config pointer_action1 move 
bspc config pointer_action2 resize_side 
bspc config pointer_action3 resize_corner 


# Padding
bspc config left_padding	$padding 
bspc config right_padding       $padding  
bspc config top_padding         $padding 
bspc config bottom_padding	$padding 

bspc config remove_disabled_monitors true 


#### BSPWM coloring ####
bspc config normal_border_color			"#3a0f66"
bspc config active_border_color			"#1e1e1e"
bspc config focused_border_color		"#7d4ab0"
bspc config presel_feedback_color		"#7d4ab0"
#bspc config urgent_border_color 	      "#dd2727"

# App Specific
bspc rule -a "GeForce NOW" state=floating 
bspc rule -a "Firefox" desktop='^2'
bspc rule -a "Discord" desktop='^5'
bspc rule -a "Signal" desktop='^6'
bspc rule -a "spotify" desktop='^7'
bspc rule -a "celluloid" desktop='^9'
