#! /bin/sh

# Vars
padding=0

# Autostart
sxhkd & 
picom & 
dunst &
nitrogen --restore & 
polybar mainbar-bspwm & 
polybar bspwm_two & 

# Misc Settings
xsetroot -cursor_name left_ptr &    # Make sure to keep the cursor a pointer when not on window
xinput set-prop 14 306 1	    # Set natural scrolling to true


# Monitors
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 
bspc monitor HDMI-2 -d 1 2 3 4 5 6 7 8 9


# Config
bspc config border_width         2	    # Width of window border
bspc config window_gap		 10	    # Gap between windows
bspc config split_ratio          0.50	    # 
bspc config borderless_monocle   true	    #
bspc config gapless_monocle      true	    #
bspc config focus_follows_pointer false 
bspc config pointer_action1 move 
bspc config pointer_action2 resize_side 
bspc config pointer_action3 resize_corner 


# Padding
bspc config left_padding	$padding 
bspc config right_padding       $padding  
bspc config top_padding         $padding 
bspc config bottom_padding	$padding 

bspc config remove_disabled_monitors true 


#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
#bspc config urgent_border_color 	      "#dd2727"

# App Specific
bspc rule -a "GeForce NOW" state=floating 
