#! /bin/sh

# Vars
padding=0

# Autostart
sxhkd & 
picom & 
polybar mainbar-bspwm & 
dunst &
redshift -l 52.007229:5.556170 &
nitrogen --restore & 
st & # Launch a terminal by default 
xautolock -time 10 -locker slock &

# If a ssecond monitor is connected, open second bar
second_mon_connection=`xrandr -- query | grep "HDMI-2" | awk '{print $2}'`
if [[ $second_mon_connection != "disconnected" ]]; then 
    polybar bspwm_two & 
    bspc monitor HDMI-2 -d 10 11 
fi

# Misc Settings
xsetroot -cursor_name left_ptr &    # Make sure to keep the cursor a pointer when not on window
xinput set-prop 'ELAN1300:00 04F3:3057 Touchpad' "libinput Tapping Enabled" 1 # Set Tapping
xinput set-prop 'ELAN1300:00 04F3:3057 Touchpad' "libinput Natural Scrolling Enabled" 1 # Enable Natural Scrolling



# Monitors
bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7 8 9 

# Config
bspc config border_width         2	    # Width of window border
bspc config window_gap		 10	    # Gap between windows
bspc config split_ratio          0.50	    # 
bspc config borderless_monocle   true	    #
bspc config gapless_monocle      true	    #
bspc config focus_follows_pointer false 
bspc config pointer_action1 move 
bspc config pointer_action2 resize_side 
bspc config pointer_action3 resize_corner 


# Padding
bspc config left_padding	$padding 
bspc config right_padding       $padding  
bspc config top_padding         $padding 
bspc config bottom_padding	$padding 

bspc config remove_disabled_monitors true 


#### BSPWM coloring ####
bspc config normal_border_color			"#3a0f66"
bspc config active_border_color			"#1e1e1e"
bspc config focused_border_color		"#7d4ab0"
bspc config presel_feedback_color		"#7d4ab0"
#bspc config urgent_border_color 	      "#dd2727"

# App Specific
bspc rule -a "GeForce NOW" state=floating 
bspc rule -a firefox desktop='^2'
bspc rule -a "Discord" desktop='^5'
bspc rule -a "Signal" desktop='^6'
bspc rule -a "spotify" desktop='^7'
bspc rule -a "celluloid" desktop='^9'
bspc rule -a "Zathura" state=tiled
